### ISSUE TITLE
create_transaction / create_transfer do not work

### ISSUE THREAD

**Issue by denys-abramov-dev** [dionysio/spendee#6]
Hi there 👋

Thanks for your library. Very useful for me.
But i have bumped into 1 problem - 2 endpoints do not work (create_transaction/create_transfer). 
Probably server receives request and responses with status 200 and created transaction in response, but after request i can't see new transaction in my spendee's profile.

Simple code example.
<img width="592" alt="Screenshot 2022-04-03 at 23 10 08" src="https://user-images.githubusercontent.com/66158129/161446501-841cde55-4bd0-4c73-82ab-ed6a93b1ab14.png">

if i pass wrong arguments in create_transaction method (category id which is not exist and etc) python says response.status is not 200.
If i use another endpoints (create category for example) - everything is ok.

**Comment by ppuppala** [comment]
Hey @denys-abramov-dev @dionysio - I'm running into this issue now. @denys-abramov-dev - you marked this as completed already, what was your fix?

When I do the `create_transaction` call, I get a response back that appears as if the transaction was created. When I do the `wallet_get_transactions` call, I see this transaction as well. However, when I open the Spendee app on my phone and refresh the list, I don't see this transaction. I've checked timestamps and things as well, and even tried to make this new transaction on a previous date to see if that affects anything, but no luck still. I would appreciate any guidance/help to figure out what's going wrong!

**Comment by dionysio** [comment]
hey @ppuppala, as far as I remember, Spendee had two major versions. This repo is for the older version of the API (and the app itself). Whatever you create through this API won't show up in the newest version of the app :(

I'm sorry, but I stopped using the app a while ago, so I gave up on this repo.
